apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: local-flow-ide
  namespace: local-flow-ide
spec:
  rules:
  - host: ide.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: local-flow-ide-service
            port:
              number: 80
