apiVersion: v1
kind: Service
metadata:
  name: local-flow-ide-service
  namespace: local-flow-ide
spec:
  selector:
    app: local-flow-ide
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
